### ISSUE TITLE
Persona 5 List Design

### ISSUE THREAD

**Issue by goodryan4** [rl404/MyAnimeList#1]
Hello,

I just wanted to let you know that the Persona 5 anime list seems to have a limit of 300 anime. I love the Design but can't use it due to the weird limit.

**Comment by rl404** [comment]
I remembered that I was also having this problem. 
It should be fixed now but the theme doesn't have the parallax effect anymore.

I also fixed all image URL.
 (why the hell I linked the images to my other theme)

**Comment by goodryan4** [comment]
Thanks for the quick fix. I don't see any other issues.
